### PR TITLE
Updated library with Vertical animation (that can be changed from xml itself)and using it up with RecyclerView.

### PR DESCRIPTION
**Pull request by sachinvarma**
Hi wajahat,
I have added Vertical flip animation which can be changed from xml itself, (Like ,app:flipType="horizontal") and made an example in which it will show how  flipView can be used in RecyclerView also (Before it was not scrollable in RecyclerView).
Thank you.

### CODE REVIEW

**Comment by wajahatkarim3** [comment]
Hello @sachinvarma 
A BIGG! Thank you for your pull request and time to put in EasyFlipView. 👍  I will merge it and upload in on jCenter() soon and will let you know :) Thanks Again!!!!

**Comment by sachinvarma** [comment]
First of all, sorry for the late reply and thanks for accepting the
contribution.

**Comment by wajahatkarim3** [comment]
Very much appreciated for your contributions. It means a lot. Thanks

**Comment by sachinvarma** [comment]
Its just an adding of some features for which a pretty good library that
you have already created, actually i am the one to thank you, because of
that library only i was able to complete one of my project. Thanks alot.

**Comment by wajahatkarim3** [comment]
Glad to hear that the library came in handy for your project. Also, is it possible that you share the app link (if live on Google play)? I will add it as showcase for this library.

**Comment by sachinvarma** [comment]
Hi karim, The project is signed with NDA. When i use it in an app which is
not signed with NDA i will surely let you know. Even these apps can't be
added to my CV also. :( . Sorry mahn..

**Pull request merged**
